version: '3.1'


services:

  adminer:
    depends_on:
      - db
    image: adminer
    restart: always
    ports:
      - 8087:8080

  db:
    image: postgres
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: daedalus_db
    ports:
      - 5432:5432

volumes:
  pg_data:
